// 供 unplugin-auto-import 使用的按需导入解析器。
// 使用方无需显式 import 组件，只要在 JSX 中书写 <Button /> 即会自动注入：
// import { Button } from "aurora-ui"

export const auroraComponentNames = [
  "Affix",
  "Alert",
  "Anchor",
  "AutoComplete",
  "Avatar",
  "AvatarGroup",
  "BackTop",
  "Badge",
  "Breadcrumb",
  "Button",
  "Calendar",
  "Card",
  "CardMeta",
  "Carousel",
  "Cascader",
  "Checkbox",
  "CheckboxGroup",
  "Col",
  "Collapse",
  "ColorPicker",
  "Countdown",
  "DatePicker",
  "Descriptions",
  "Divider",
  "Drawer",
  "Dropdown",
  "Empty",
  "Flex",
  "FloatButton",
  "Form",
  "FormItem",
  "Header",
  "Icon",
  "Image",
  "InfiniteScroll",
  "Input",
  "InputNumber",
  "Layout",
  "Link",
  "List",
  "Mentions",
  "Menu",
  "MessageHolder",
  "Modal",
  "ModalHolder",
  "NotificationHolder",
  "Pagination",
  "Paragraph",
  "Popconfirm",
  "Popover",
  "Progress",
  "Radio",
  "RadioGroup",
  "RangePicker",
  "Rate",
  "Result",
  "Row",
  "Segmented",
  "Select",
  "Sider",
  "Skeleton",
  "Slider",
  "Sortable",
  "Space",
  "SpaceCompact",
  "Spin",
  "Statistic",
  "Steps",
  "Switch",
  "Table",
  "Tabs",
  "Tag",
  "Text",
  "TextArea",
  "TimePicker",
  "Timeline",
  "Title",
  "Tooltip",
  "Tour",
  "Transfer",
  "Tree",
  "TreeSelect",
  "Typography",
  "Upload",
  "Watermark",
] as const

export interface AuroraAutoImportResolver {
  resolve: (name: string) => { name: string; from: string } | undefined
}

export const AuroraUIResolver: AuroraAutoImportResolver = {
  resolve(name: string) {
    if ((auroraComponentNames as readonly string[]).includes(name)) {
      return { name, from: "aurora-ui" }
    }
    return undefined
  },
}
